import './dashboard.scss';
import util from '../../helpers/util';

const drawDashbaord = () => {
  let domString = '';
  domString += '<div class="container">';
  domString += '<div class="row">';
  domString += '  <div class="col-12 col-sm-10 offset-sm-1">';
  domString += '    <div class="row">';
  domString += '      <div class="col-12 col-md-6">';
  domString += '        <div class="card">';
  domString += '          <div class="img-contain">';
  domString += '          <img class="img-fluid dashboard-img" src="../assets/images/dashboard/diary.png" alt="">';
  domString += '          </div>';
  domString += '          <div class="card-body">';
  domString += '            <h5 class="card-title">Card title</h5>';
  domString += '            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the';
  domString += '              card\'s content.</p>';
  domString += '            <a href="#" class="btn btn-primary">Go somewhere</a>';
  domString += '          </div>';
  domString += '        </div>';
  domString += '      </div>';
  domString += '      <div class="col-12 col-md-6">';
  domString += '        <div class="card">';
  domString += '          <div class="img-contain">';
  domString += '          <img class="img-fluid dashboard-img" src="../assets/images/dashboard/diary.png" alt="">';
  domString += '          </div>';
  domString += '          <div class="card-body">';
  domString += '            <h5 class="card-title">Card title</h5>';
  domString += '            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the';
  domString += '              card\'s content.</p>';
  domString += '            <a href="#" class="btn btn-primary">Go somewhere</a>';
  domString += '          </div>';
  domString += '        </div>';
  domString += '      </div>';
  domString += '      <div class="col-12 col-md-6">';
  domString += '        <div class="card">';
  domString += '          <div class="img-contain">';
  domString += '          <img class="img-fluid dashboard-img" src="../assets/images/dashboard/diary.png" alt="">';
  domString += '          </div>';
  domString += '          <div class="card-body">';
  domString += '            <h5 class="card-title">Card title</h5>';
  domString += '            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the';
  domString += '              card\'s content.</p>';
  domString += '            <a href="#" class="btn btn-primary">Go somewhere</a>';
  domString += '          </div>';
  domString += '        </div>';
  domString += '      </div>';
  domString += '      <div class="col-12 col-md-6">';
  domString += '        <div class="card">';
  domString += '          <div class="img-contain">';
  domString += '          <img class="img-fluid dashboard-img" src="../assets/images/dashboard/diary.png" alt="">';
  domString += '          </div>';
  domString += '          <div class="card-body">';
  domString += '            <h5 class="card-title">Card title</h5>';
  domString += '            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the';
  domString += '              card\'s content.</p>';
  domString += '            <a href="#" class="btn btn-primary">Go somewhere</a>';
  domString += '          </div>';
  domString += '        </div>';
  domString += '      </div>';
  domString += '    </div>';
  domString += '  </div>';
  domString += '</div>';
  domString += '</div>';
  util.printToDom('dashboard-div', domString);
};

export default { drawDashbaord };
